version: "3.7"

services:
  anime_quiz:
    build:
      context: .
    networks:
      - anime_quiz
      - server
    ports:
      - 8009:8009
    depends_on:
      - celery_worker
    volumes:
      - ./static:/usr/src/app/static:rw
    restart: unless-stopped
  celery_worker:
    build:
      context: .
    entrypoint: celery -A anime_quiz worker
    networks:
      - anime_quiz
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:6.0
    networks:
      - anime_quiz
    restart: unless-stopped

networks:
  server:
    external: true
  anime_quiz:
